### ISSUE TITLE
error：Maximum call stack size exceeded

### ISSUE THREAD

**Issue by xuhongv** [EspressifApp/EspEyeForWeChat#1]
- 配网过程中，监听到设备发来的特征值之后报错：

```
[publib]:1 thirdScriptError
Maximum call stack size exceeded;at api notifyBLECharacteristicValueChanged success callback function
RangeError: Maximum call stack size exceeded
```

- 经过断点调试，发现是在 blueConnect.js 发现 调用下面这个报错：
```
 self.setData({
      client: client
    });
```

**Comment by xuhongv** [comment]
![image](https://user-images.githubusercontent.com/25237870/69617623-6e895980-1073-11ea-9109-597e72a66ab0.png)

**Comment by ESP32-S31** [comment]
可以将client定义了到外面
<img width="530" alt="屏幕快照 2019-11-26 下午7 10 13" src="https://user-images.githubusercontent.com/13268758/69624882-726fa880-1080-11ea-8e5d-75d3b21396f4.png">
